---
title: "11-19-19"
author: "Amy Tan"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)
library(skimr)
library(fs)
library(dplyr)
library(rstanarm)
library(tidyverse)
```


```{r read_data}

download.file("https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile="master.zip")

unzip("master.zip")

my_list <- fs::dir_ls("2018-live-poll-results-master/data/")

y<- map_dfr(my_list, read_csv,
             col_types=cols(
              .default= col_character(),
              turnout_scale = col_double(),
              turnout_score = col_double(),
              w_LV = col_double(),
              w_RV = col_double(),
              final_weight = col_double(),
              timestamp  = col_datetime(format = "")
              ),
            .id = "source")
fs::file_delete(c("master.zip", "2018-live-poll-results-master"))
```

```{r}
z<- y %>% 
  mutate(dvote = ifelse(response == "Dem", 1, 0)) %>% 
  mutate(female = ifelse(gender == "Female", 1, 0)) %>% 
  select(dvote, female, response, gender)

#model that connects dvote and female

z_model <- glm(formula = dvote ~female, data=z, family="binomial")
summary(z_model)

new_data <- z %>%
  mutate(prediction = predict(z_model, type = "response"))

my_data <- tibble(female = c(0, 0, 1))

predict(z_model, newdata = my_data, type = "response")


```

